version: "2"

services:
  logio:
    image: temal/logio-server
    networks:
     - chaosnet
    ports:
      - "28778:28778"
    volumes_from:
      - storage

  logio_havester:
    image: temal/logio-harvester
    depends_on:
      - logio
    networks:
     - chaosnet
    volumes_from:
      - storage

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:db
    networks:
     - chaosnet
    ports:
      - 82:80