version: "2" #CMD: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --force-recreate

services:
  logio:
    image: temal/logio-server
    networks:
     - chaosnet
    ports:
      - "28778:28778"
    restart: always
    volumes_from:
      - storage

  logio_havester:
    image: temal/logio-harvester
    depends_on:
      - logio
    networks:
     - chaosnet
    restart: always
    volumes:
      - ./services/logio:/home/logio/.log.io
    volumes_from:
      - storage

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:db
    networks:
     - chaosnet
    ports:
      - 82:80
    restart: always
