version: "2"

services:
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead_123
    networks:
      - chaosnet
    ports:
      - "3306:3306"
    volumes_from:
      - storage

  nginx:
    image: chaos/nginx:1.13-alpine
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    depends_on:
      - storage
      - mysql
      - rabbitmq
    networks:
      - chaosnet
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - storage

  php7:
    image: chaos/php:7.1-fpm-alpine
    build:
      context: ./services/php
      dockerfile: Dockerfile
    networks:
      - chaosnet
    volumes_from:
      - storage

  rabbitmq:
    image: rabbitmq:3.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=homestead
      - RABBITMQ_DEFAULT_PASS=homestead_123
    networks:
      - chaosnet
    ports:
      - "15672:15672"

  redis:
    image: redis:3.0-alpine
    networks:
      - chaosnet
    ports:
      - "6379:6379"

  storage:
    image: chaos/storage:latest
    build:
      context: ./services/storage
      dockerfile: Dockerfile
    environment:
      - UNISON_WORKING_DIR=/var/chaos
    networks:
      - chaosnet
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - mysql_lib:/var/lib/mysql
      - nginx_log:/var/log/nginx
      - ./homestead:/var/chaos
      - ./services/logio:/home/logio/.log.io
      - ./services/mysql:/docker-entrypoint-initdb.d
      - ./services/nginx/certs:/etc/nginx/certs
      - ./services/nginx/conf.d:/etc/nginx/conf.d

volumes:
  mysql_lib: {}
  nginx_log: {}

networks:
  chaosnet:
    driver: bridge
