version: "2"

services:
  mysql:
    container_name: chaos_mysql
    image: mariadb:10.1
    ports:
    - "3306:3306"
    volumes_from:
      - storage
    environment:
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    container_name: chaos_nginx
    image: nginx:1.11-alpine
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes_from:
      - storage

  php:
    container_name: chaos_php
    image: php:7.1-fpm-alpine
    volumes_from:
      - storage

  redis:
    container_name: chaos_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  storage:
    container_name: chaos_storage
    image: leighmcculloch/unison:latest
    ports:
      - "5000:5000"
    volumes:
      - db:/var/lib/mysql
      - log_nginx:/var/log/nginx
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    environment:
      - UNISON_WORKING_DIR=/var/chaos

volumes:
  db: {}
  log_nginx: {}

networks:
  default:
    driver: bridge
