version: "2"

services:
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo123
    networks:
     - chaosnet
    ports:
    - "3306:3306"
    stdin_open: true
    volumes_from:
      - storage

  nginx:
    image: nginx:1.11-alpine
    networks:
     - chaosnet
    ports:
      - "80:80"
    volumes_from:
      - storage

  php:
    image: php:7.1-fpm-alpine
    networks:
     - chaosnet
    stdin_open: true
    volumes_from:
      - storage

  gearman:
    image: contemi/noria-gearmand
    networks:
     - chaosnet
    ports:
      - "4730:4730"
    volumes_from:
      - storage

  rabbitmq:
    image: rabbitmq:3.6.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo123
    networks:
     - chaosnet
    ports:
      - "15672:15672"

  redis:
    image: redis:alpine
    networks:
     - chaosnet
    ports:
      - "6379:6379"
    stdin_open: true

  storage:
    image: leighmcculloch/unison:latest
    environment:
      - UNISON_WORKING_DIR=/var/chaos
    networks:
     - chaosnet
    ports:
      - "5000:5000"
    volumes:
      - db:/var/lib/mysql
      - log_nginx:/var/log/nginx
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html

volumes:
  db: {}
  log_nginx: {}

networks:
  chaosnet:
    driver: bridge
