version: "2"

services:
  logio:
    container_name: logio
    image: temal/logio-server
    ports:
      - "28778:28778"
    restart: always
    volumes_from:
      - storage

  logio_havester:
    container_name: logio_havester
    image: temal/logio-harvester
    depends_on:
      - logio
    restart: always
    volumes_from:
      - storage

  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    volumes_from:
      - storage
    environment:
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    container_name: nginx
    image: nginx:1.11-alpine
    depends_on:
      - mariadb
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes_from:
      - storage

  phpfpm:
    container_name: phpfpm
    image: php:fpm
    volumes_from:
      - storage

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - mariadb:db
    ports:
      - 81:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root

  redis:
    container_name: redis
    image: redis:alpine

  storage:
    container_name: storage
    image: leighmcculloch/unison:latest
    ports:
      - "5000:5000"
    volumes:
      - db:/var/lib/mysql
      - log_nginx:/var/log/nginx
      - ./.docker/logio:/home/logio/.log.io
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    environment:
      - UNISON_WORKING_DIR=/var/chaos

volumes:
  db: {}
  log_nginx: {}

networks:
  default:
    driver: bridge
