version: "2" #CMD: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --force-recreate

services:
  logio:
    container_name: chaos_logio
    image: temal/logio-server
    ports:
      - "28778:28778"
    restart: always
    volumes_from:
      - storage

  logio_havester:
    container_name: chaos_logio_havester
    image: temal/logio-harvester
    depends_on:
      - logio
    restart: always
    volumes:
      - ./.docker/logio:/home/logio/.log.io
    volumes_from:
      - storage

  phpmyadmin:
    container_name: chaos_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - mysql:db
    ports:
      - 81:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  db: {}
  log_nginx: {}

networks:
  default:
    driver: bridge
