version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx:1.11-alpine
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./.docker/nginx:/var/log/nginx

  phpfpm:
    container_name: phpfpm
    image: php:fpm
    volumes:
     - ./www:/usr/share/nginx/html

  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - mariadb:db
    ports:
      - 81:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root

  logio:
    container_name: logio
    image: temal/logio-server
    ports:
      - "28778:28778"
    restart: always
    volumes:
      - ./.docker/logio:/home/logio/.log.io

  logio_havester:
    container_name: logio_havester
    image: temal/logio-harvester
    links:
      - logio
    restart: always
    volumes:
      - ./.docker/logio:/home/logio/.log.io
    volumes_from:
      - nginx

networks:
  default:
    driver: bridge
