version: "2"

services:
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead12345
    networks:
      - chaosnet
    ports:
      - "3306:3306"
    volumes_from:
      - storage

  nginx:
    image: nginx:1.11-alpine
    networks:
      - chaosnet
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - storage

  php:
    image: php:7.1-fpm-alpine
    networks:
      - chaosnet
    volumes_from:
      - storage

  rabbitmq:
    image: rabbitmq:3.6.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=homestead
      - RABBITMQ_DEFAULT_PASS=homestead12345
    networks:
      - chaosnet
    ports:
      - "15672:15672"

  redis:
    image: redis:3.0-alpine
    networks:
      - chaosnet
    ports:
      - "6379:6379"

  storage:
    image: leighmcculloch/unison:latest
    environment:
      - UNISON_WORKING_DIR=/unison
    networks:
      - chaosnet
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - logs:/var/log/nginx
      - ./services/nginx:/etc/nginx/conf.d
      - ./services/php/php.ini:/usr/local/etc/php/php.ini
      - ./homestead:/usr/share/nginx/html

volumes:
  db: {}
  logs: {}

networks:
  chaosnet:
    driver: bridge
