version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx:1.11-alpine
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/error.log:/var/log/nginx/error.log
      - ./.docker/nginx/access.log:/var/log/nginx/access.log

  phpfpm:
    container_name: phpfpm
    image: php:fpm
    volumes:
      - ./www:/usr/share/nginx/html

  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - mariadb:db
    ports:
      - 81:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root

  logio:
    container_name: logio
    image: temal/logio-server
    ports:
      - "28778:28778"
      - "28777:28777"
    restart: always
    volumes:
      - ./.docker/logio:/home/logio/.log.io

  logio_havester:
    container_name: logio_havester
    image: temal/logio-harvester
    links:
      - logio
    restart: always
    volumes:
      - ./.docker/logio:/home/logio/.log.io
    volumes_from:
      - nginx

networks:
  default:
    driver: bridge
